/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Aplikasi_Gudang_Norlaila;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author ACER
 */
public class tb_barangMasuk extends javax.swing.JFrame {
    DefaultTableModel mod;
    private String SQL;
    /**
     * Creates new form tb_barangMasuk
     * @throws java.sql.SQLException
     */
    public tb_barangMasuk()  throws SQLException{
        initComponents();
        bersih();
        tampilData();
        setLocationRelativeTo(this);
    }
    private void bersih(){
        txidbm.setText(null);
        txid.setText(null);
        txtgl.setText(null);
        txjm.setText(null);
        
    }
private void tampilData() throws SQLException{
    mod = new DefaultTableModel();
    mod.addColumn("id_bm");
    mod.addColumn("id_barang");
    mod.addColumn("tgl_masuk");
    mod.addColumn("jumlah");
    tabel.setModel(mod);
    Connection conn=koneksi.getConnection();
    try{
        java.sql.Statement stmt = conn.createStatement();
        SQL ="select * from tb_barangmasuk";
        java.sql.ResultSet res = stmt.executeQuery(SQL);
        while(res.next()){
            mod.addRow(new Object[]{
                res.getString("id_bm"),
                res.getString("id_barang"),
                res.getString("tgl_masuk"),
                res.getString("jumlah")
            });
            }
        }
    catch (SQLException e){
    System.out.println(e);
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txidbm = new javax.swing.JTextField();
        txid = new javax.swing.JTextField();
        txtgl = new javax.swing.JTextField();
        txjm = new javax.swing.JTextField();
        btnread = new javax.swing.JButton();
        btncreate = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btnkeluar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("BARANG MASUK");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, -1, -1));

        jLabel2.setText("ID Barang Masuk");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 59, -1, -1));

        jLabel3.setText("ID Barang");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 85, -1, -1));

        jLabel4.setText("Tanggal Masuk");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 114, -1, -1));

        jLabel5.setText("Jumlah");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 143, -1, -1));

        txidbm.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.add(txidbm, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 59, 103, -1));

        txid.setBackground(new java.awt.Color(0, 204, 204));
        txid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txidActionPerformed(evt);
            }
        });
        jPanel1.add(txid, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 86, 103, -1));

        txtgl.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.add(txtgl, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 114, 103, -1));

        txjm.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.add(txjm, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 140, 103, -1));

        btnread.setBackground(new java.awt.Color(0, 153, 153));
        btnread.setText("Read");
        btnread.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreadActionPerformed(evt);
            }
        });
        jPanel1.add(btnread, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 185, -1, -1));

        btncreate.setBackground(new java.awt.Color(0, 153, 153));
        btncreate.setText("Create");
        btncreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncreateActionPerformed(evt);
            }
        });
        jPanel1.add(btncreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 185, -1, -1));

        btnupdate.setBackground(new java.awt.Color(0, 153, 153));
        btnupdate.setText("Update");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });
        jPanel1.add(btnupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 185, -1, -1));

        btndelete.setBackground(new java.awt.Color(0, 153, 153));
        btndelete.setText("Delete");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btndelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(291, 185, -1, -1));

        btnkeluar.setBackground(new java.awt.Color(0, 153, 153));
        btnkeluar.setText("Keluar");
        btnkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkeluarActionPerformed(evt);
            }
        });
        jPanel1.add(btnkeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(283, 85, -1, -1));

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 226, -1, 97));

        jButton1.setBackground(new java.awt.Color(0, 153, 153));
        jButton1.setText("Cetak");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(372, 185, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Aplikasi_Gudang_Norlaila/bawang putih.jpg"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 340));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txidActionPerformed

    }//GEN-LAST:event_txidActionPerformed

    private void btnreadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreadActionPerformed
        // TODO add your handling code here:
        try{
            Connection conn = koneksi.getConnection();
            PreparedStatement stmt = conn.prepareStatement
        ("insert into tb_barangmasuk (id_bm, id_barang, tgl_masuk, jumlah)value(?, ?, ?, ?)");
            stmt.setString(1, txidbm.getText());
            stmt.setString(2, txid.getText());
            stmt.setString(3, txtgl.getText());
            stmt.setString(4, txjm.getText());
            stmt.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Berhasil di Simpan ", "Pesan", JOptionPane.INFORMATION_MESSAGE);
            tampilData();
            bersih();
        }catch (SQLException e){
            System.out.println(e);
        } 
    }//GEN-LAST:event_btnreadActionPerformed

    private void btncreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncreateActionPerformed
        // TODO add your handling code here:
         try{
            Connection conn = koneksi.getConnection();
            PreparedStatement stmt = conn.prepareStatement
        ("insert into tb_barangmasuk (id_bm, id_barang, tgl_masuk, jumlah)value(?, ?, ?, ?)");
            stmt.setString(1, txidbm.getText());
            stmt.setString(2, txid.getText());
            stmt.setString(3, txtgl.getText());
            stmt.setString(4, txjm.getText());
            stmt.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Berhasil di Ubah ", "Pesan", JOptionPane.INFORMATION_MESSAGE);
            tampilData();
            bersih();
        }catch (SQLException e){
            System.out.println(e);
        } 
    }//GEN-LAST:event_btncreateActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        // TODO add your handling code here:
        try{
        String sql = "UPDATE tb_barangmasuk SET id_barang ='"+txid.getText()+"', tgl_masuk='"+txtgl.getText()+"', jumlah='"+txjm.getText()+"'WHERE  id_bm='"+txidbm.getText()+"'";
        java.sql.Connection conn = (Connection)koneksi.getConnection();
        java.sql.PreparedStatement stmt = conn.prepareStatement(sql);
        stmt.execute();
        JOptionPane.showMessageDialog(null, "Data Berhasil di Update");
    }catch (SQLException e){
        JOptionPane.showMessageDialog(null,"Data Gagal diUpdate"+ e.getMessage());
    }
   
        try {
            tampilData();
        } catch (SQLException ex) {
            Logger.getLogger(tb_stok.class.getName()).log(Level.SEVERE, null, ex);
        }
         bersih();
    }//GEN-LAST:event_btnupdateActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        // TODO add your handling code here:
        int i =tabel.getSelectedRow();
        if(i== -1) {
            return;
        }
        
        String id_bm = (String)mod.getValueAt(i, 0);
        int question = JOptionPane.showConfirmDialog(null, "Apakah Anda Yakin Ingin Hapus data?", "Konfirmasi", JOptionPane.OK_CANCEL_OPTION,
                JOptionPane.QUESTION_MESSAGE);
        if(question == JOptionPane.OK_OPTION){
            try{
                Connection c = koneksi.getConnection();
                String sql = "DELETE FROM tb_barangmasuk WHERE id_bm= ?";
                try (PreparedStatement p = c.prepareStatement(sql)) {
                    p.setString(1, id_bm);
                    p.executeUpdate();
                }
                JOptionPane.showMessageDialog(null, "Data terhapus");
            }catch (SQLException e){
                System.out.println(e);
            }
        }
        if (question == JOptionPane.CANCEL_OPTION){
            
        }
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btnkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkeluarActionPerformed
        // TODO add your handling code here:
        formUtama xx;
        xx = new formUtama();
        xx.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnkeluarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         try{
         JasperPrint jp = JasperFillManager.fillReport(getClass().getResourceAsStream("report1.jasper"), null, koneksi.getConnection());
         JasperViewer.viewReport(jp, false); 
         
      }catch (JRException e){
          JOptionPane.showMessageDialog(rootPane, e);
      }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMouseClicked
        // TODO add your handling code here:
        try{
               Connection conn = koneksi.getConnection();
               int row = tabel.getSelectedRow();
               String tabel_klik = (tabel.getModel().getValueAt(row, 0).toString());
               java.sql.Statement stmt = conn.createStatement();
               java.sql.ResultSet sql = stmt.executeQuery("select * from tb_barangmasuk where  id_bm = '"+tabel_klik+"'");
               if (sql.next()){
                   String id_bm=sql.getString("id_bm");
                   txidbm.setText(id_bm);
                   String id_barang=sql.getString("id_barang");
                   txid.setText(id_barang);
                   String tgl_masuk=sql.getString("tgl_masuk");
                   txtgl.setText(tgl_masuk);
                   String jumlah=sql.getString("jumlah");
                   txjm.setText(jumlah);
               }
           }catch (SQLException e){}
    }//GEN-LAST:event_tabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tb_barangMasuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new tb_barangMasuk().setVisible(true);
            } catch (SQLException ex) {
                Logger.getLogger(tb_barangMasuk.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncreate;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnkeluar;
    private javax.swing.JButton btnread;
    private javax.swing.JButton btnupdate;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabel;
    private javax.swing.JTextField txid;
    private javax.swing.JTextField txidbm;
    private javax.swing.JTextField txjm;
    private javax.swing.JTextField txtgl;
    // End of variables declaration//GEN-END:variables

   
}
