/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Aplikasi_Gudang_Norlaila;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author ACER
 */
public class tb_barangKeluar extends javax.swing.JFrame {
    DefaultTableModel mod;
    private String SQL;
    /**
     * Creates new form tb_barangKeluar
     * @throws java.sql.SQLException
     */
    public tb_barangKeluar()  throws SQLException{
        initComponents();
        bersih();
        tampilData();
        setLocationRelativeTo(this);
    }
    private void bersih(){
        txidbk.setText(null);
        txid.setText(null);
        txtgl.setText(null);
        txjm.setText(null);
    }
    private void tampilData() throws SQLException{
    mod = new DefaultTableModel();
    mod.addColumn("id_bk");
    mod.addColumn("id_barang");
    mod.addColumn("tgl_keluar");
    mod.addColumn("jumlah");
    tabel.setModel(mod);
    Connection conn=koneksi.getConnection();
    try{
        java.sql.Statement stmt = conn.createStatement();
        SQL ="select * from tb_barangkeluar";
        java.sql.ResultSet res = stmt.executeQuery(SQL);
        while(res.next()){
            mod.addRow(new Object[]{
                res.getString("id_bk"),
                res.getString("id_barang"),
                res.getString("tgl_keluar"),
                res.getString("jumlah")
            });
            }
        }
    catch (SQLException e){
    System.out.println(e);
    }
}
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txidbk = new javax.swing.JTextField();
        txid = new javax.swing.JTextField();
        txtgl = new javax.swing.JTextField();
        txjm = new javax.swing.JTextField();
        btnkeluar = new javax.swing.JButton();
        btnread = new javax.swing.JButton();
        btncreate = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 0, 204));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 204, 204));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("BARANG KELUAR");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, -1, -1));

        jLabel2.setBackground(new java.awt.Color(0, 204, 204));
        jLabel2.setText("ID Barang Keluar");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        jLabel3.setBackground(new java.awt.Color(0, 204, 204));
        jLabel3.setText("ID Barang");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        jLabel4.setBackground(new java.awt.Color(0, 204, 204));
        jLabel4.setText("Tanggal Keluar");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        jLabel5.setBackground(new java.awt.Color(0, 204, 204));
        jLabel5.setText("Jumlah");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        txidbk.setBackground(new java.awt.Color(0, 204, 204));
        getContentPane().add(txidbk, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 92, -1));

        txid.setBackground(new java.awt.Color(0, 204, 204));
        getContentPane().add(txid, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 92, -1));

        txtgl.setBackground(new java.awt.Color(0, 204, 204));
        getContentPane().add(txtgl, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 92, -1));

        txjm.setBackground(new java.awt.Color(0, 204, 204));
        getContentPane().add(txjm, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 92, -1));

        btnkeluar.setBackground(new java.awt.Color(0, 153, 153));
        btnkeluar.setText("Keluar");
        btnkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkeluarActionPerformed(evt);
            }
        });
        getContentPane().add(btnkeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 108, -1, -1));

        btnread.setBackground(new java.awt.Color(0, 153, 153));
        btnread.setText("Read");
        btnread.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreadActionPerformed(evt);
            }
        });
        getContentPane().add(btnread, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 213, -1, -1));

        btncreate.setBackground(new java.awt.Color(0, 153, 153));
        btncreate.setText("Create");
        btncreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncreateActionPerformed(evt);
            }
        });
        getContentPane().add(btncreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 213, -1, -1));

        btnupdate.setBackground(new java.awt.Color(0, 153, 153));
        btnupdate.setText("Update");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 213, -1, -1));

        btndelete.setBackground(new java.awt.Color(0, 153, 153));
        btndelete.setText("Delete");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btndelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 213, -1, -1));

        jScrollPane1.setBackground(new java.awt.Color(0, 204, 204));

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 247, -1, 92));

        jButton1.setBackground(new java.awt.Color(0, 153, 153));
        jButton1.setText("Cetak");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 213, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Aplikasi_Gudang_Norlaila/bawang putih.jpg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnreadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreadActionPerformed
        // TODO add your handling code here:
        try{
            Connection conn = koneksi.getConnection();
            PreparedStatement stmt = conn.prepareStatement
        ("insert into tb_barangkeluar (id_bk, id_barang, tgl_keluar, jumlah)value(?, ?, ?, ?)");
            stmt.setString(1, txidbk.getText());
            stmt.setString(2, txid.getText());
            stmt.setString(3, txtgl.getText());
            stmt.setString(4, txjm.getText());
            stmt.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Berhasil di Simpan ", "Pesan", JOptionPane.INFORMATION_MESSAGE);
            tampilData();
            bersih();
        }catch (SQLException e){
            System.out.println(e);
        } 
    }//GEN-LAST:event_btnreadActionPerformed

    private void btncreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncreateActionPerformed
        // TODO add your handling code here:
        try{
            Connection conn = koneksi.getConnection();
            PreparedStatement stmt = conn.prepareStatement
        ("insert into tb_barangkeluar (id_bk, id_barang, tgl_keluar, jumlah)value(?, ?, ?, ?)");
            stmt.setString(1, txidbk.getText());
            stmt.setString(2, txid.getText());
            stmt.setString(3, txtgl.getText());
            stmt.setString(4, txjm.getText());
            stmt.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Berhasil di Ubah ", "Pesan", JOptionPane.INFORMATION_MESSAGE);
            tampilData();
            bersih();
        }catch (SQLException e){
            System.out.println(e);
        } 
    }//GEN-LAST:event_btncreateActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        // TODO add your handling code here:
        try{
        String sql = "UPDATE tb_barangkeluar SET id_barang ='"+txid.getText()+"', tgl_keluar='"+txtgl.getText()+"', jumlah='"+txjm.getText()+"'WHERE  id_bk='"+txidbk.getText()+"'";
        java.sql.Connection conn = (Connection)koneksi.getConnection();
        java.sql.PreparedStatement stmt = conn.prepareStatement(sql);
        stmt.execute();
        JOptionPane.showMessageDialog(null, "Data Berhasil di Update");
    }catch (SQLException e){
        JOptionPane.showMessageDialog(null,"Data Gagal diUpdate"+ e.getMessage());
    }
   
        try {
            tampilData();
        } catch (SQLException ex) {
            Logger.getLogger(tb_stok.class.getName()).log(Level.SEVERE, null, ex);
        }
         bersih();
    }//GEN-LAST:event_btnupdateActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        // TODO add your handling code here:
        int i =tabel.getSelectedRow();
        if(i== -1) {
            return;
        }
        
        String id_bk = (String)mod.getValueAt(i, 0);
        int question = JOptionPane.showConfirmDialog(null, "Apakah Anda Yakin Ingin Hapus data?", "Konfirmasi", JOptionPane.OK_CANCEL_OPTION,
                JOptionPane.QUESTION_MESSAGE);
        if(question == JOptionPane.OK_OPTION){
            try{
                Connection c = koneksi.getConnection();
                String sql = "DELETE FROM tb_barangkeluar WHERE id_bk= ?";
                try (PreparedStatement p = c.prepareStatement(sql)) {
                   
                    p.setString(1, id_bk);
                    p.executeUpdate();
                }
                JOptionPane.showMessageDialog(null, "Data terhapus");
            }catch (SQLException e){
                System.out.println(e);
            }
        }
        if (question == JOptionPane.CANCEL_OPTION){
            
        }
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btnkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkeluarActionPerformed
        // TODO add your handling code here:
        formUtama xx;
        xx = new formUtama();
        xx.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnkeluarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         try{
         JasperPrint jp = JasperFillManager.fillReport(getClass().getResourceAsStream("report2.jasper"), null, koneksi.getConnection());
         JasperViewer.viewReport(jp, false); 
         
      }catch (JRException e){
          JOptionPane.showMessageDialog(rootPane, e);
      }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMouseClicked
        // TODO add your handling code here:
        try{
               Connection conn = koneksi.getConnection();
               int row = tabel.getSelectedRow();
               String tabel_klik = (tabel.getModel().getValueAt(row, 0).toString());
               java.sql.Statement stmt = conn.createStatement();
               java.sql.ResultSet sql = stmt.executeQuery("select * from tb_barangkeluar where  id_bk = '"+tabel_klik+"'");
               if (sql.next()){
                   String id_bk=sql.getString("id_bk");
                   txidbk.setText(id_bk);
                   String id_barang=sql.getString("id_barang");
                   txid.setText(id_barang);
                   String tgl_keluar=sql.getString("tgl_keluar");
                   txtgl.setText(tgl_keluar);
                   String jumlah=sql.getString("jumlah");
                   txjm.setText(jumlah);
               }
           }catch (SQLException e){}
    }//GEN-LAST:event_tabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tb_barangKeluar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tb_barangKeluar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tb_barangKeluar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tb_barangKeluar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new tb_barangKeluar().setVisible(true);
            } catch (SQLException ex) {
                Logger.getLogger(tb_barangKeluar.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncreate;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnkeluar;
    private javax.swing.JButton btnread;
    private javax.swing.JButton btnupdate;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabel;
    private javax.swing.JTextField txid;
    private javax.swing.JTextField txidbk;
    private javax.swing.JTextField txjm;
    private javax.swing.JTextField txtgl;
    // End of variables declaration//GEN-END:variables
}
